name: Pylint & Black & iSort

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint, black, isort
    - name: Analysing the code with pylint, black & isort
      run: |
        pylint $(git ls-files '*.py')
        black $(git ls-files '*.py')
        isort $(git ls-files '*.py')
